package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/anthropics/agentmesh/backend/internal/api/graphql/generated"
	"github.com/anthropics/agentmesh/backend/internal/domain/agent"
	"github.com/anthropics/agentmesh/backend/internal/domain/agentpod"
	"github.com/anthropics/agentmesh/backend/internal/domain/channel"
	"github.com/anthropics/agentmesh/backend/internal/domain/gitprovider"
	"github.com/anthropics/agentmesh/backend/internal/domain/organization"
	"github.com/anthropics/agentmesh/backend/internal/domain/runner"
	"github.com/anthropics/agentmesh/backend/internal/domain/ticket"
	"github.com/anthropics/agentmesh/backend/internal/domain/user"
)

// CredentialSchema is the resolver for the credentialSchema field.
func (r *agentTypeResolver) CredentialSchema(ctx context.Context, obj *agent.AgentType) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: CredentialSchema - credentialSchema"))
}

// Messages is the resolver for the messages field.
func (r *channelResolver) Messages(ctx context.Context, obj *channel.Channel, limit *int, offset *int) ([]generated.ChannelMessage, error) {
	panic(fmt.Errorf("not implemented: Messages - messages"))
}

// Pods is the resolver for the pods field.
func (r *channelResolver) Pods(ctx context.Context, obj *channel.Channel) ([]agentpod.Pod, error) {
	panic(fmt.Errorf("not implemented: Pods - pods"))
}

// CredentialSchema is the resolver for the credentialSchema field.
func (r *customAgentTypeResolver) CredentialSchema(ctx context.Context, obj *agent.CustomAgentType) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: CredentialSchema - credentialSchema"))
}

// StatusDetection is the resolver for the statusDetection field.
func (r *customAgentTypeResolver) StatusDetection(ctx context.Context, obj *agent.CustomAgentType) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: StatusDetection - statusDetection"))
}

// CreatePod is the resolver for the createPod field.
func (r *mutationResolver) CreatePod(ctx context.Context, input generated.CreatePodInput) (*agentpod.Pod, error) {
	panic(fmt.Errorf("not implemented: CreatePod - createPod"))
}

// TerminatePod is the resolver for the terminatePod field.
func (r *mutationResolver) TerminatePod(ctx context.Context, key string) (*agentpod.Pod, error) {
	panic(fmt.Errorf("not implemented: TerminatePod - terminatePod"))
}

// CreateTicket is the resolver for the createTicket field.
func (r *mutationResolver) CreateTicket(ctx context.Context, input generated.CreateTicketInput) (*ticket.Ticket, error) {
	panic(fmt.Errorf("not implemented: CreateTicket - createTicket"))
}

// UpdateTicket is the resolver for the updateTicket field.
func (r *mutationResolver) UpdateTicket(ctx context.Context, identifier string, input generated.UpdateTicketInput) (*ticket.Ticket, error) {
	panic(fmt.Errorf("not implemented: UpdateTicket - updateTicket"))
}

// DeleteTicket is the resolver for the deleteTicket field.
func (r *mutationResolver) DeleteTicket(ctx context.Context, identifier string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTicket - deleteTicket"))
}

// UpdateTicketStatus is the resolver for the updateTicketStatus field.
func (r *mutationResolver) UpdateTicketStatus(ctx context.Context, identifier string, status generated.TicketStatus) (*ticket.Ticket, error) {
	panic(fmt.Errorf("not implemented: UpdateTicketStatus - updateTicketStatus"))
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, name string, color string, repositoryID *int64) (*ticket.Label, error) {
	panic(fmt.Errorf("not implemented: CreateLabel - createLabel"))
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, id int64) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteLabel - deleteLabel"))
}

// CreateChannel is the resolver for the createChannel field.
func (r *mutationResolver) CreateChannel(ctx context.Context, input generated.CreateChannelInput) (*channel.Channel, error) {
	panic(fmt.Errorf("not implemented: CreateChannel - createChannel"))
}

// UpdateChannel is the resolver for the updateChannel field.
func (r *mutationResolver) UpdateChannel(ctx context.Context, id int64, input generated.UpdateChannelInput) (*channel.Channel, error) {
	panic(fmt.Errorf("not implemented: UpdateChannel - updateChannel"))
}

// ArchiveChannel is the resolver for the archiveChannel field.
func (r *mutationResolver) ArchiveChannel(ctx context.Context, id int64) (*channel.Channel, error) {
	panic(fmt.Errorf("not implemented: ArchiveChannel - archiveChannel"))
}

// UnarchiveChannel is the resolver for the unarchiveChannel field.
func (r *mutationResolver) UnarchiveChannel(ctx context.Context, id int64) (*channel.Channel, error) {
	panic(fmt.Errorf("not implemented: UnarchiveChannel - unarchiveChannel"))
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, channelID int64, content string, podKey *string) (*generated.ChannelMessage, error) {
	panic(fmt.Errorf("not implemented: SendMessage - sendMessage"))
}

// JoinChannel is the resolver for the joinChannel field.
func (r *mutationResolver) JoinChannel(ctx context.Context, channelID int64, podKey string) (bool, error) {
	panic(fmt.Errorf("not implemented: JoinChannel - joinChannel"))
}

// LeaveChannel is the resolver for the leaveChannel field.
func (r *mutationResolver) LeaveChannel(ctx context.Context, channelID int64, podKey string) (bool, error) {
	panic(fmt.Errorf("not implemented: LeaveChannel - leaveChannel"))
}

// Members is the resolver for the members field.
func (r *organizationResolver) Members(ctx context.Context, obj *organization.Organization) ([]generated.OrganizationMember, error) {
	panic(fmt.Errorf("not implemented: Members - members"))
}

// Runners is the resolver for the runners field.
func (r *organizationResolver) Runners(ctx context.Context, obj *organization.Organization) ([]runner.Runner, error) {
	panic(fmt.Errorf("not implemented: Runners - runners"))
}

// Status is the resolver for the status field.
func (r *podResolver) Status(ctx context.Context, obj *agentpod.Pod) (generated.PodStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// Repository is the resolver for the repository field.
func (r *podResolver) Repository(ctx context.Context, obj *agentpod.Pod) (*gitprovider.Repository, error) {
	panic(fmt.Errorf("not implemented: Repository - repository"))
}

// Ticket is the resolver for the ticket field.
func (r *podResolver) Ticket(ctx context.Context, obj *agentpod.Pod) (*ticket.Ticket, error) {
	panic(fmt.Errorf("not implemented: Ticket - ticket"))
}

// CreatedBy is the resolver for the createdBy field.
func (r *podResolver) CreatedBy(ctx context.Context, obj *agentpod.Pod) (*user.User, error) {
	panic(fmt.Errorf("not implemented: CreatedBy - createdBy"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id int64) (*user.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, slug string) (*organization.Organization, error) {
	panic(fmt.Errorf("not implemented: Organization - organization"))
}

// MyOrganizations is the resolver for the myOrganizations field.
func (r *queryResolver) MyOrganizations(ctx context.Context) ([]organization.Organization, error) {
	panic(fmt.Errorf("not implemented: MyOrganizations - myOrganizations"))
}

// Runner is the resolver for the runner field.
func (r *queryResolver) Runner(ctx context.Context, id int64) (*runner.Runner, error) {
	panic(fmt.Errorf("not implemented: Runner - runner"))
}

// Runners is the resolver for the runners field.
func (r *queryResolver) Runners(ctx context.Context, status *generated.RunnerStatus) ([]runner.Runner, error) {
	panic(fmt.Errorf("not implemented: Runners - runners"))
}

// AvailableRunners is the resolver for the availableRunners field.
func (r *queryResolver) AvailableRunners(ctx context.Context) ([]runner.Runner, error) {
	panic(fmt.Errorf("not implemented: AvailableRunners - availableRunners"))
}

// Pod is the resolver for the pod field.
func (r *queryResolver) Pod(ctx context.Context, key string) (*agentpod.Pod, error) {
	panic(fmt.Errorf("not implemented: Pod - pod"))
}

// Pods is the resolver for the pods field.
func (r *queryResolver) Pods(ctx context.Context, filter *generated.PodFilter, first *int, after *string) (*generated.PodConnection, error) {
	panic(fmt.Errorf("not implemented: Pods - pods"))
}

// AgentTypes is the resolver for the agentTypes field.
func (r *queryResolver) AgentTypes(ctx context.Context) ([]agent.AgentType, error) {
	panic(fmt.Errorf("not implemented: AgentTypes - agentTypes"))
}

// AgentType is the resolver for the agentType field.
func (r *queryResolver) AgentType(ctx context.Context, id int64) (*agent.AgentType, error) {
	panic(fmt.Errorf("not implemented: AgentType - agentType"))
}

// CustomAgentTypes is the resolver for the customAgentTypes field.
func (r *queryResolver) CustomAgentTypes(ctx context.Context) ([]agent.CustomAgentType, error) {
	panic(fmt.Errorf("not implemented: CustomAgentTypes - customAgentTypes"))
}

// Repository is the resolver for the repository field.
func (r *queryResolver) Repository(ctx context.Context, id int64) (*gitprovider.Repository, error) {
	panic(fmt.Errorf("not implemented: Repository - repository"))
}

// Repositories is the resolver for the repositories field.
func (r *queryResolver) Repositories(ctx context.Context) ([]gitprovider.Repository, error) {
	panic(fmt.Errorf("not implemented: Repositories - repositories"))
}

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, identifier string) (*ticket.Ticket, error) {
	panic(fmt.Errorf("not implemented: Ticket - ticket"))
}

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context, filter *generated.TicketFilter, first *int, after *string) (*generated.TicketConnection, error) {
	panic(fmt.Errorf("not implemented: Tickets - tickets"))
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context, repositoryID *int64) ([]ticket.Label, error) {
	panic(fmt.Errorf("not implemented: Labels - labels"))
}

// Channel is the resolver for the channel field.
func (r *queryResolver) Channel(ctx context.Context, id int64) (*channel.Channel, error) {
	panic(fmt.Errorf("not implemented: Channel - channel"))
}

// Channels is the resolver for the channels field.
func (r *queryResolver) Channels(ctx context.Context, includeArchived *bool) ([]channel.Channel, error) {
	panic(fmt.Errorf("not implemented: Channels - channels"))
}

// GitProviders is the resolver for the gitProviders field.
func (r *queryResolver) GitProviders(ctx context.Context) ([]gitprovider.GitProvider, error) {
	panic(fmt.Errorf("not implemented: GitProviders - gitProviders"))
}

// Status is the resolver for the status field.
func (r *runnerResolver) Status(ctx context.Context, obj *runner.Runner) (generated.RunnerStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// HostInfo is the resolver for the hostInfo field.
func (r *runnerResolver) HostInfo(ctx context.Context, obj *runner.Runner) (map[string]any, error) {
	panic(fmt.Errorf("not implemented: HostInfo - hostInfo"))
}

// ActivePods is the resolver for the activePods field.
func (r *runnerResolver) ActivePods(ctx context.Context, obj *runner.Runner) ([]agentpod.Pod, error) {
	panic(fmt.Errorf("not implemented: ActivePods - activePods"))
}

// PodUpdated is the resolver for the podUpdated field.
func (r *subscriptionResolver) PodUpdated(ctx context.Context, key string) (<-chan *agentpod.Pod, error) {
	panic(fmt.Errorf("not implemented: PodUpdated - podUpdated"))
}

// MessageReceived is the resolver for the messageReceived field.
func (r *subscriptionResolver) MessageReceived(ctx context.Context, channelID int64) (<-chan *generated.ChannelMessage, error) {
	panic(fmt.Errorf("not implemented: MessageReceived - messageReceived"))
}

// RunnerStatusChanged is the resolver for the runnerStatusChanged field.
func (r *subscriptionResolver) RunnerStatusChanged(ctx context.Context) (<-chan *runner.Runner, error) {
	panic(fmt.Errorf("not implemented: RunnerStatusChanged - runnerStatusChanged"))
}

// Type is the resolver for the type field.
func (r *ticketResolver) Type(ctx context.Context, obj *ticket.Ticket) (generated.TicketType, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// Status is the resolver for the status field.
func (r *ticketResolver) Status(ctx context.Context, obj *ticket.Ticket) (generated.TicketStatus, error) {
	panic(fmt.Errorf("not implemented: Status - status"))
}

// Priority is the resolver for the priority field.
func (r *ticketResolver) Priority(ctx context.Context, obj *ticket.Ticket) (generated.TicketPriority, error) {
	panic(fmt.Errorf("not implemented: Priority - priority"))
}

// Reporter is the resolver for the reporter field.
func (r *ticketResolver) Reporter(ctx context.Context, obj *ticket.Ticket) (*user.User, error) {
	panic(fmt.Errorf("not implemented: Reporter - reporter"))
}

// Assignees is the resolver for the assignees field.
func (r *ticketResolver) Assignees(ctx context.Context, obj *ticket.Ticket) ([]user.User, error) {
	panic(fmt.Errorf("not implemented: Assignees - assignees"))
}

// Pods is the resolver for the pods field.
func (r *ticketResolver) Pods(ctx context.Context, obj *ticket.Ticket) ([]agentpod.Pod, error) {
	panic(fmt.Errorf("not implemented: Pods - pods"))
}

// ChildTickets is the resolver for the childTickets field.
func (r *ticketResolver) ChildTickets(ctx context.Context, obj *ticket.Ticket) ([]ticket.Ticket, error) {
	panic(fmt.Errorf("not implemented: ChildTickets - childTickets"))
}

// ParentTicket is the resolver for the parentTicket field.
func (r *ticketResolver) ParentTicket(ctx context.Context, obj *ticket.Ticket) (*ticket.Ticket, error) {
	panic(fmt.Errorf("not implemented: ParentTicket - parentTicket"))
}

// Organizations is the resolver for the organizations field.
func (r *userResolver) Organizations(ctx context.Context, obj *user.User) ([]organization.Organization, error) {
	panic(fmt.Errorf("not implemented: Organizations - organizations"))
}

// AgentType returns generated.AgentTypeResolver implementation.
func (r *Resolver) AgentType() generated.AgentTypeResolver { return &agentTypeResolver{r} }

// Channel returns generated.ChannelResolver implementation.
func (r *Resolver) Channel() generated.ChannelResolver { return &channelResolver{r} }

// CustomAgentType returns generated.CustomAgentTypeResolver implementation.
func (r *Resolver) CustomAgentType() generated.CustomAgentTypeResolver {
	return &customAgentTypeResolver{r}
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Organization returns generated.OrganizationResolver implementation.
func (r *Resolver) Organization() generated.OrganizationResolver { return &organizationResolver{r} }

// Pod returns generated.PodResolver implementation.
func (r *Resolver) Pod() generated.PodResolver { return &podResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Runner returns generated.RunnerResolver implementation.
func (r *Resolver) Runner() generated.RunnerResolver { return &runnerResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// Ticket returns generated.TicketResolver implementation.
func (r *Resolver) Ticket() generated.TicketResolver { return &ticketResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type agentTypeResolver struct{ *Resolver }
type channelResolver struct{ *Resolver }
type customAgentTypeResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type organizationResolver struct{ *Resolver }
type podResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type runnerResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type ticketResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *runnerResolver) CurrentPods(ctx context.Context, obj *runner.Runner) (int, error) {
	panic(fmt.Errorf("not implemented: CurrentPods - currentPods"))
}
*/
